//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojistikApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Urunler> UrunlerSet { get; set; }
        public virtual DbSet<Personeller> PersonellerSet { get; set; }
        public virtual DbSet<Departman> DepartmanSet { get; set; }
        public virtual DbSet<TasiyiciFirmalar> TasiyiciFirmalarSet { get; set; }
        public virtual DbSet<UreticiFirmalar> UreticiFirmalarSet { get; set; }
        public virtual DbSet<AliciFirmalar> AliciFirmalarSet { get; set; }
        public virtual DbSet<Sevkiyat> SevkiyatSet { get; set; }
        public virtual DbSet<Firmalar> FirmalarSet { get; set; }
    }
}
