//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojistikApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sevkiyat
    {
        public int sevkiyat_id { get; set; }
        public string SevkAdi { get; set; }
        public string Ulke { get; set; }
        public int Urunler_urun_id { get; set; }
        public int Firmalar_firma_id { get; set; }
    
        public virtual Urunler Urunler { get; set; }
        public virtual Firmalar Firmalar { get; set; }
    }
}
