//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojistikApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasiyiciFirmalar
    {
        public int tasiyici_id { get; set; }
        public string TFirmaAdi { get; set; }
        public string TFirmaAdresi { get; set; }
        public string TFirmaTel { get; set; }
        public string TasimaSekli { get; set; }
        public int Firmalar_firma_id { get; set; }
    
        public virtual Firmalar Firmalar { get; set; }
    }
}
